-d C:\Users\Joe\dev\brus16\gowin\impl\gwsynthesis\tn9k.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Joe\dev\brus16\gowin\src\tn9k\9k.cst
-cfg C:\Users\Joe\dev\brus16\gowin\impl\pnr\device.cfg
-sdc C:\Users\Joe\dev\brus16\gowin\src\tn9k\9k.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
