-d C:\Users\Joe\dev\brus16\gowin\impl\gwsynthesis\gowin.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Joe\dev\brus16\gowin\src\gowin.cst
-cfg C:\Users\Joe\dev\brus16\gowin\impl\pnr\device.cfg
-sdc C:\Users\Joe\dev\brus16\gowin\src\gowin.sdc
-bit
-tr
-ph
-sdf
-posp
-o
-tt
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-no_cst_warning
-convert_sdp32_36_to_sdp16_18
-place_option 1
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 64
-global_freq 50.000
