--lint-only
./src/alu.v
./src/brus16_controller.v
./src/brus16_top.v
./src/bsram.v
./src/btree_mux_layer.v
./src/btree_mux.v
./src/button_handler.v
./src/button_controller.v
./src/comparator.v
./src/cpu.v
./src/dsram.v
./src/gpu_mem.v
./src/gpu.v
./src/rect_copy_controller.v
./src/stack.v
./src/vga_controller.v
-Wall

